---
title: "Consumos con Tarjeta de Crédito - Abril 2016"
author: "Javier Adanaque"
output:
  flexdashboard::flex_dashboard:
    vertical_layout: fill
    theme: flatly
---

```{r setup, include=FALSE}
library(flexdashboard)
library(magrittr)
library(plotly)
library(tidyverse)
library(lubridate)
library(RColorBrewer)
library(ggthemes)
library(extrafont)
library(stringr)
library(waffle)
#library(googleVis)

# Reading data
db_consumos <- read_csv("data/query_output-consumos_abril.csv")

names(db_consumos) <- tolower(names(db_consumos))

```

An&aacute;lisis
=======================================================================


Column1 {data-width=530}
-----------------------------------------------------------------------

### 1. Distribuci&oacute;n Diaria

```{r calendario}
# Grouping and summarizing
db_consumos <- db_consumos %>%
  mutate(fecha = ymd(fecha))

db_consumos_daily <- db_consumos %>%
  group_by(fecha) %>%
  summarize(importe = sum(importe)) %>%
  mutate(dia_sem = wday(fecha),
         dia_sem_label = wday(fecha, label = TRUE),
         semana = isoweek(fecha+1))
  


pcal <- ggplot(db_consumos_daily, aes(semana, -dia_sem, fill = importe)) +
  geom_tile(colour = "#9C0824") +
  scale_fill_continuous_tableau() +
  scale_y_continuous(breaks = -7:-1, labels = c("Sab", "Vie", "Jue", "Mie", "Mar", "Lun", "Dom")) +
  scale_x_continuous(breaks = NULL) +
  labs(y = NULL,
       x = NULL) +
  theme_minimal() +
  theme(panel.grid.major.y = element_blank(),
        panel.grid.minor.y = element_blank(),
        legend.position = "right",
        legend.direction = "vertical")
#scale_fill_continuous(low = "#F0F8FF", high = "#08306b")

pcal <- plotly_build(pcal)

pcal$x$data[[1]]$text <- with(arrange(db_consumos_daily, semana, desc(dia_sem)),
                                matrix(paste0("Fecha: ", c(fecha[1:2], rep(NA, 5), fecha[3:30]), "<br>Importe: ",
                                c(importe[1:2], rep(NA, 5), importe[3:30])), nrow = 7, ncol = 5))
# pcal$x$data[[1]]$hoverinfo <- "text"

pcal  # Todo: outline colors
```

### 2. Macrogiros

```{r macrogiros}
# Consideramos sólo el comportamiento sabatino, que observamos que es donde hay mayor consumo con tarjeta
p_macrogiro <- db_consumos %>%
    filter(fecha %in% ymd(c('20160402','20160409','20160416', '20160423','20160430'))) %>%
    group_by(macrogiro) %>%
    summarize(importe = sum(importe)) %>%
    mutate(importe_prop = importe/sum(importe),
           macrogiro2 = ifelse(importe_prop > 0.0169, macrogiro, "Otros")) %>%
    group_by(macrogiro2) %>%
    summarize(importe = sum(importe)) %>%
    mutate(importe_prop = importe / sum(importe)) %>%
    ggplot(aes(importe_prop, reorder(macrogiro2, importe_prop))) +
    geom_segment(aes(yend = macrogiro2), xend = 0, colour = "grey50") +
    geom_point(colour = "#9C0824") +
    scale_x_continuous(breaks = seq(0, 0.4, 0.05), labels = paste0(seq(0, 0.4, 0.05)*100, "%")) +
    labs(x = "Proporción de Consumo Sabatino",
         y = NULL) +
    theme_bw() +
    theme(panel.grid.major.x = element_blank(),
          panel.grid.minor.x = element_blank(),
          panel.grid.major.y = element_line(colour = "grey80", linetype = "dashed"))
#scale_y_discrete(labels = c("Tiendas/Almacenes Departamentales" = "Tdas./Almac. Departamentales")) +

p_macrogiro <- plotly_build(p_macrogiro)

p_macrogiro$x$data[[2]]$text <- gsub("reorder\\(|, importe_prop\\)", "", p_macrogiro$x$data[[2]]$text)

p_macrogiro

```

Column2 {data-width=470}
-----------------------------------------------------------------------

### 3. Tiendas de Principales Macrogiros

```{r macrogiros_tiendas}
db_consumos_tienda <- db_consumos %>%
  filter(fecha %in% ymd(c('20160402','20160409','20160416', '20160423','20160430'))) %>%
  group_by(macrogiro) %>%
  mutate(importe_macro = sum(importe)) %>%
  ungroup() %>%
  filter(importe_macro/sum(importe) > 0.1) %>%  # Observaciones (transacciones) cuyo macrogiro represente más del 10% del consumo sabatino
  mutate(tienda_corregida = str_trim(gsub("[0-9]*", "", tienda)))

for (i in 1:nrow(db_consumos_tienda)) {
  if (str_detect(db_consumos_tienda$tienda_corregida[i], "CARSA")) {
    db_consumos_tienda$tienda_corregida[i] <- "CARSA"
  } else if (str_detect(db_consumos_tienda$tienda_corregida[i], "[vV][eE][Aa]")) {
      db_consumos_tienda$tienda_corregida[i] <- "PLAZA VEA"
  } else if (str_detect(db_consumos_tienda$tienda_corregida[i], "[Ww][oO][nN][gG]")) {
      db_consumos_tienda$tienda_corregida[i] <- "E WONG"
  } else if (str_detect(db_consumos_tienda$tienda_corregida[i], "(?i)hiraoka")) {
      db_consumos_tienda$tienda_corregida[i] <- "HIRAOKA"
  } else if (str_detect(db_consumos_tienda$tienda_corregida[i], "(?i)metro")) {
      db_consumos_tienda$tienda_corregida[i] <- "METRO"
  } else if (str_detect(db_consumos_tienda$tienda_corregida[i], "(?i)TOP[IY] ?TOP")) {
      db_consumos_tienda$tienda_corregida[i] <- "TOPITOP"
  } else if (str_detect(db_consumos_tienda$tienda_corregida[i], "(?i)TOTTUS")) {
      db_consumos_tienda$tienda_corregida[i] <- "TOTTUS"
  } else if (str_detect(db_consumos_tienda$tienda_corregida[i], "(?i)CURACAO")) {
      db_consumos_tienda$tienda_corregida[i] <- "CURACAO"
  } else if (str_detect(db_consumos_tienda$tienda_corregida[i], "(?i)ELEKTRA")) {
      db_consumos_tienda$tienda_corregida[i] <- "ELEKTRA"
  } else if (str_detect(db_consumos_tienda$tienda_corregida[i], "(?i)EFE")) {
      db_consumos_tienda$tienda_corregida[i] <- "TIENDAS EFE"
  } else if (str_detect(db_consumos_tienda$tienda_corregida[i], "(?i)BATAWA")) {
      db_consumos_tienda$tienda_corregida[i] <- "BATAWA"  # Only one insignificant transaction. Used only to keep it different from BATA
  } else if (str_detect(db_consumos_tienda$tienda_corregida[i], "(?i)BATA")) {
      db_consumos_tienda$tienda_corregida[i] <- "BATA"
  } else if (str_detect(db_consumos_tienda$tienda_corregida[i], "(?i)pass?arela")) {
      db_consumos_tienda$tienda_corregida[i] <- "PASSARELA"
  } else if (str_detect(db_consumos_tienda$tienda_corregida[i], "(?i)hilfiger")) {
      db_consumos_tienda$tienda_corregida[i] <- "HILFIGER"
  } else if (str_detect(db_consumos_tienda$tienda_corregida[i], "(?i)platan")) {
      db_consumos_tienda$tienda_corregida[i] <- "PLATANITOS"
  }
}

db_consumos_tienda <- db_consumos_tienda %>%
  group_by(macrogiro, tienda_corregida) %>%
  summarise(importe = sum(importe),
            n = n()) %>%
  filter(row_number(desc(importe)) <= 5) %>%
  ungroup

p_macr_tienda <- ggplot(db_consumos_tienda, aes(importe, reorder(tienda_corregida, importe))) +
  geom_segment(aes(yend = tienda_corregida), xend = 0, colour = "grey50") +
  geom_point(colour = "#9c0824") +
  scale_x_continuous(expand = c(0.02, 0)) +
  facet_grid(macrogiro ~ ., scales="free_y") +
  labs(x = "Consumo Sabatino en Soles",
       y = NULL) +
  theme_bw() +
  theme(panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        panel.grid.major.y = element_line(colour = "grey80", linetype = "dashed"))

p_macr_tienda <- plotly_build(p_macr_tienda)

# 4-6
for (i in 4:6) {
  p_macr_tienda$x$data[[i]]$text <- gsub("reorder\\(|, importe\\)", "", p_macr_tienda$x$data[[i]]$text)
  p_macr_tienda$x$data[[i]]$text <- gsub("tienda_corregida", "Tienda", p_macr_tienda$x$data[[i]]$text)
  p_macr_tienda$x$data[[i]]$text <- gsub("importe", "Importe", p_macr_tienda$x$data[[i]]$text)
}

for (i in 1:3) {
  p_macr_tienda$x$data[[i]]$hoverinfo <- "none"
}

p_macr_tienda

# ptrns <- c("vivanda", "tottus", "hiraoka", "mass")
# sapply(paste0("(?i)", ptrns), function(pt){
#     db_consumos_tienda %>%
#         filter(str_detect(tienda_corregida, pt)) %>%
#         summarise(importe = sum(importe))
# })

```

### 4. Tiendas Top: #Transacciones Sabatinas

```{r tiendastop_transacciones, fig.width=8, fig.height=5}
transacciones <- db_consumos_tienda$n
names(transacciones) <- db_consumos_tienda$tienda_corregida

transacciones <- transacciones[transacciones>20]

p_tdas_transacc <- waffle(sort(transacciones, decreasing = TRUE)/5, rows = 14, size = 1, colors = tableau_color_pal("tableau20")(11)) +
  labs(x = "1 cuadrado = 5 transacciones") +
  theme(axis.title.x = element_text(face = "bold", size = 12))

print(p_tdas_transacc)
```

SQL {data-orientation=rows}
=======================================================================

Row1 {data-height=200}
-----------------------------------------------------------------------

### SQL Query

```
SELECT FECTRA AS FECHA, DESCMCGIR AS MACROGIRO, DESCGIRCOM AS GIRO, DESMOV AS TIENDA, SUM(IMPAFE) AS IMPORTE
FROM BDFINANCIERA.consumos_abril_mayo2016
WHERE FECTRA<20160501
GROUP BY FECTRA, DESCMCGIR, DESCGIRCOM, DESMOV
ORDER BY FECTRA, DESCMCGIR, DESCGIRCOM, DESMOV
```
> El query se ejecutó en MySQL y el resultado se exportó a formato CSV.
> Como siempre, la data requirió más procesamiento para realizar el análisis. Este  procesamiento y análisis se trabajó en R.

Row2 {data-height=800}
-----------------------------------------------------------------------

### SQL Query Output

```{r}
DT::datatable(sample_n(db_consumos, 1000),
              caption = 'Query Output: Arroja 94,361 registros. Aquí se observa sólo una muestra aleatoria de 1,000.'
              )
```
